### ISSUE TITLE
Azure function failed to log

### ISSUE THREAD

**Issue by maksym-synkevych** [logzio/logzio-logback-appender#61]
Filed to log java-based Azure function using logback appender. Logging works properly when I'm running the application locally, but failed when trying to run it on Azure Function App environment with the following error: 
```
2019-10-11T11:09:03.943 [Information] java.lang.IllegalStateException: Logback configuration error detected:
2019-10-11T11:09:03.943 [Information] ERROR in ch.qos.logback.core.joran.spi.Interpreter@14:16 - RuntimeException in Action for tag [appender] java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@4af18225 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@5283b3c5[Shutting down, pool size = 3, active threads = 0, queued tasks = 0, completed tasks = 2]
```
Full stacktrace available in here
[logzio-appender.log](https://github.com/logzio/logzio-logback-appender/files/3717295/logzio-appender.log)
.
Here is my configuration (real token replaced by "token" world):
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <include resource="org/springframework/boot/logging/logback/defaults.xml"/>
    <include resource="org/springframework/boot/logging/logback/console-appender.xml"/>
    <shutdownHook class="ch.qos.logback.core.hook.DelayingShutdownHook"/>
    <appender name="LOGZIO" class="io.logz.logback.LogzioLogbackAppender">
        <token>token</token>
        <logzioUrl>https://listener-nl.logz.io:8071</logzioUrl>
        <logzioType>azure-function</logzioType>
    </appender>
    <root level="DEBUG">
        <appender-ref ref="CONSOLE"/>
        <appender-ref ref="LOGZIO"/>
    </root>
    <logger name="org.springframework.web" level="DEBUG"/>
</configuration>

```

**Comment by idohalevi** [comment]
@maksym-synkevych It looks like the error is related to the logging fw. Can you try it with the console appender only and tell me if you have an issue or not?

**Comment by maksym-synkevych** [comment]
@idohalevi Tried with only console appender and it is also failed.

**Comment by idohalevi** [comment]
@maksym-synkevych Please remove the token from the configuration sample. 
Can you provide the logs for the error?

**Comment by maksym-synkevych** [comment]
@idohalevi Updated previous message by removing the token.
You can see logs in attachments.
[logzio-appender.log](https://github.com/logzio/logzio-logback-appender/files/3778357/logzio-appender.log)

**Comment by idohalevi** [comment]
@maksym-synkevych Can you add the versions of the logback & logz.io appender? In addition, can you sure a snapshot of the project structure, specifically where is your logback.xml configuration and the naming of the files?

**Comment by maksym-synkevych** [comment]
@idohalevi The version of logzio appender is 1.0.22
The project structure is following
![image](https://user-images.githubusercontent.com/7526230/67753862-12b0be00-fa3e-11e9-8f99-5b38b2525ef0.png)

**Comment by idohalevi** [comment]
@maksym-synkevych Can you try the fix [here](https://github.com/spring-projects/spring-boot/issues/3472)? rename `logback.xml` to `logback-spring.xml`

**Comment by maksym-synkevych** [comment]
@idohalevi Still failing with the same error:
```
2019-10-29T13:52:49.854 [Information] 2019-10-29 13:52:49.837 ERROR 9124 --- [pool-2-thread-2] o.s.boot.SpringApplication               : Application run failed
2019-10-29T13:52:49.854 [Information] java.lang.IllegalStateException: Logback configuration error detected:
2019-10-29T13:52:49.854 [Information] ERROR in ch.qos.logback.core.joran.spi.Interpreter@10:16 - RuntimeException in Action for tag [appender] java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@62b08a6e rejected from java.util.concurrent.ScheduledThreadPoolExecutor@5a59fc85[Shutting down, pool size = 6, active threads = 0, queued tasks = 0, completed tasks = 3]
2019-10-29T13:52:49.854 [Information] at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:166)
2019-10-29T13:52:49.854 [Information] at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:79)
2019-10-29T13:52:49.854 [Information] at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:59)
2019-10-29T13:52:49.855 [Information] at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:117)
2019-10-29T13:52:49.855 [Information] at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:279)
2019-10-29T13:52:49.855 [Information] at org.springframework.boot.context.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:254)
```
